### ISSUE TITLE
Doesn't build with `indexmap` `2.1`

### ISSUE THREAD

**Issue by Vollkornaffe** [garro95/priority-queue#56]
So, I'm not 100% sure this is an issue on this crate.
(It might also be a violation of semantic versioning on `indexmap` side)

If you add the minor version to the dependency, this should be fixed.
E.g., `2.5`.

You can reproduce the issue by pinning the version to `2.1`, and you'll get something like
```
error[E0599]: the method `get_index_mut2` exists for struct `IndexMap<I, P, H>`, but its trait bounds were not satisfied
  --> src/double_priority_queue/iterators.rs:93:14 
  ```

**Comment by garro95** [comment]
Thanks for reporting.
